In [6]:
import numpy as np

# Task 1: Create a 3×3 array filled with random numbers and print its shape
array_random = np.random.rand(3, 3)
print("3x3 Random Array:\n", array_random)
print("Shape:", array_random.shape)

# Task 2: Convert an array of floats [1.1, 2.2, 3.3] into integers
float_array = np.array([1.1, 2.2, 3.3])
int_array = float_array.astype(int)
print("Converted to Integers:", int_array)

# Task 3: Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6]
original_array = np.array([1, 2, 3, 4, 5, 6])
even_indices = [i for i, x in enumerate(original_array) if x % 2 == 0]
even_numbers = original_array[even_indices]
print("Even Numbers (Fancy Indexing):", even_numbers)

# Task 4: Reshape a 1D array of size 9 into a 3×3 matrix
array_1d = np.arange(9)
array_reshaped = array_1d.reshape(3, 3)
print("Reshaped to 3x3:\n", array_reshaped)

# Task 5: Use boolean masking to filter numbers greater than 50 in an array
sample_array = np.array([10, 55, 32, 77, 49, 100])
filtered_array = sample_array[sample_array > 50]
print("Numbers Greater Than 50:", filtered_array)


3x3 Random Array:
 [[0.93270011 0.07574165 0.24316857]
 [0.12155462 0.39244861 0.2707164 ]
 [0.4383733  0.14945375 0.30824511]]
Shape: (3, 3)
Converted to Integers: [1 2 3]
Even Numbers (Fancy Indexing): [2 4 6]
Reshaped to 3x3:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Numbers Greater Than 50: [ 55  77 100]
